### ISSUE TITLE
Modify the directory structure for easier deployment

### ISSUE THREAD

**Issue by MrOrz** [littleq0903/ntpc_social_robot#8]
Since we might improve the source code every time we go deploy, keeping a ready-to-deploy zip file in the google drive seems cumbersome. Maybe we should just put everything into this repository, including `.bat` files and the directories that we put files, so that clicking "Download ZIP" on github can get us everything we need.

Here's the question: should we change the directory structure to the same as in the current zip file, or should we open up another git branch to do so?

**Comment by littleq0903** [comment]
go if you need it ;)

**Comment by MrOrz** [comment]
WIP in branch [feature/bat-files](https://github.com/littleq0903/ntpc_social_robot/tree/feature/bat-files).

Will continue next monday.

**Comment by littleq0903** [comment]
I will close this issue once we tested this in Banqiao District Office case.

**Comment by MrOrz** [comment]
Postponed :P
Actual date to Banqiao is TBA.

**Comment by MrOrz** [comment]
Verified that the new structure worked.
Setup at Banqiao ended in 1 hour!
(Debugging proxy issue in #11 took some time. Windows server 2008 sp2 does not apply the utf-8 zip patch also took some time.)
